name: fit3d
channels:
  - conda-forge
  - pytorch
  - defaults
  - pytorch3d
  - open3d-admin
  - anaconda
dependencies:
  - pip=21.1.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - python=3.7.6
  - pytorch=1.7.1
  - pytorch3d=0.4.0
  - trimesh=3.9.24
  - joblib=1.0.1
  - pip:
    - h5py==2.9.0
    - smplx==0.1.28
