[tool.flake8]
# needs to be coherent with black settings
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "lint_env",
    "env",
    "docs",
    "notebooks",
    "poc_materials",
    ".buildozer"
]
extend-ignore = [
    # Styling rules already handled by black
    "E1",
    "W1",
    "E2",
    "W2",
    "E3",
    "W3",
    "E5",
    "W5",
    # Rule too strict (no lambdas)
    "E731"
]

per-file-ignores = '''
    __init__.py: F401
'''

[tool.isort]
profile = "black"
skip_glob = ["*/venv/*", "*/env/*", "*/docs/*", "*/lint_env/*"]


[tool.black]
line-length = 120
exclude = '''
    lint_env\/|venv\/|env\/|docs\/|notebooks\/|poc\_materials\/|\.buildozer\/
'''
preview = true

[tool.pylint.'MESSAGES CONTROL']
disable = "line-too-long,missing-module-docstring,missing-function-docstring,import-error,broad-exception-caught"
