[tool.flake8]
# needs to be coherent with black settings
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "env",
    "docs",
    "notebooks",
    "poc_materials",
    ".buildozer"
]
extend-ignore = [
    # Styling rules already handled by black
    "E1",
    "W1",
    "E2",
    "W2",
    "E3",
    "W3",
    "E401",
    "E5",
    "W5",
    # Rule too strict (no lambdas)
    "E731"
]

per-file-ignores = '''
    __init__.py: F401
'''

[tool.isort]
profile = "black"
skip_glob = ["venv/*", "env/*", "docs/*"]


[tool.black]
line-length = 120
exclude = '''
    venv\/|env\/|docs\/|notebooks\/|poc\_materials\/|\.buildozer\/
'''
preview = true
